include (${CMAKE_HOME_DIRECTORY}/kernel/modules/CMakeLists.txt) # MODULES_SOURCES

file(GLOB_RECURSE INTERFACE_SOURCES 	
    ${CMAKE_CURRENT_LIST_DIR}/include/*.cpp
    ${CMAKE_CURRENT_LIST_DIR}/include/*.c 
    ${CMAKE_CURRENT_LIST_DIR}/include/*.cc
    ${CMAKE_CURRENT_LIST_DIR}/include/*.hh 
    ${CMAKE_CURRENT_LIST_DIR}/include/*.hpp 
    ${CMAKE_CURRENT_LIST_DIR}/include/*.h
    ${CMAKE_CURRENT_LIST_DIR}/impl/*.cpp
    ${CMAKE_CURRENT_LIST_DIR}/impl/*.c 
    ${CMAKE_CURRENT_LIST_DIR}/impl/*.cc
    ${CMAKE_CURRENT_LIST_DIR}/impl/*.hh 
    ${CMAKE_CURRENT_LIST_DIR}/impl/*.hpp 
    ${CMAKE_CURRENT_LIST_DIR}/impl/*.h
)
# ZEGO_SOURCE_GROUP_BY_DIR(INTERFACE_SOURCES)	

set(ALL_SOURCES_SERVER_ASSISTANT)
list(APPEND ALL_SOURCES_SERVER_ASSISTANT ${MODULES_SOURCES})
list(APPEND ALL_SOURCES_SERVER_ASSISTANT ${INTERFACE_SOURCES})

# ZEGO_SOURCE_GROUP_BY_DIR(ALL_SOURCES_SERVER_ASSISTANT)	
